-- MySQL Script generated by MySQL Workbench
-- Thu Mar 14 20:34:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema farmersdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `farmersdb` ;

-- -----------------------------------------------------
-- Schema farmersdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmersdb` DEFAULT CHARACTER SET utf8 ;
USE `farmersdb` ;

-- -----------------------------------------------------
-- Table `farmersdb`.`Farm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmersdb`.`Farm` ;

CREATE TABLE IF NOT EXISTS `farmersdb`.`Farm` (
  `farmID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `mainProduct` VARCHAR(45) NULL,
  PRIMARY KEY (`farmID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmersdb`.`Vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmersdb`.`Vendor` ;

CREATE TABLE IF NOT EXISTS `farmersdb`.`Vendor` (
  `vendorID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `stallcount` INT NULL,
  `farmID` INT NULL,
  PRIMARY KEY (`vendorID`),
  INDEX `farmID_idx` (`farmID` ASC),
  CONSTRAINT `farmID`
    FOREIGN KEY (`farmID`)
    REFERENCES `farmersdb`.`Farm` (`farmID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmersdb`.`ProductCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmersdb`.`ProductCategory` ;

CREATE TABLE IF NOT EXISTS `farmersdb`.`ProductCategory` (
  `categoryID` INT NOT NULL,
  `categoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmersdb`.`Sells`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmersdb`.`Sells` ;

CREATE TABLE IF NOT EXISTS `farmersdb`.`Sells` (
  `sellID` INT NOT NULL AUTO_INCREMENT,
  `categoryID` INT NOT NULL,
  `vendorID` INT NOT NULL,
  PRIMARY KEY (`sellID`),
  INDEX `vendorID_idx` (`vendorID` ASC),
  INDEX `categoryID_idx` (`categoryID` ASC),
  CONSTRAINT `vID`
    FOREIGN KEY (`vendorID`)
    REFERENCES `farmersdb`.`Vendor` (`vendorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cID`
    FOREIGN KEY (`categoryID`)
    REFERENCES `farmersdb`.`ProductCategory` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmersdb`.`Market`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmersdb`.`Market` ;

CREATE TABLE IF NOT EXISTS `farmersdb`.`Market` (
  `marketID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lat` DECIMAL(9,6) NOT NULL,
  `lng` DECIMAL(9,6) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `credit` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`marketID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmersdb`.`participates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmersdb`.`participates` ;

CREATE TABLE IF NOT EXISTS `farmersdb`.`participates` (
  `participationID` INT NOT NULL AUTO_INCREMENT,
  `marketID` INT NOT NULL,
  `vendorID` INT NOT NULL,
  PRIMARY KEY (`participationID`),
  INDEX `marketID_idx` (`marketID` ASC),
  INDEX `vendorID_idx` (`vendorID` ASC),
  CONSTRAINT `marketID`
    FOREIGN KEY (`marketID`)
    REFERENCES `farmersdb`.`Market` (`marketID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vendorID`
    FOREIGN KEY (`vendorID`)
    REFERENCES `farmersdb`.`Vendor` (`vendorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
